apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-default-network-policy
spec:
  background: true
  rules:
    - name: generate-default-deny-ingress
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  fleet.gitops/type: tenant
      generate:
        synchronize: true
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        name: default-deny-ingress
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            podSelector: {}
            policyTypes:
              - Ingress