apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-pod-security-profile
spec:
  background: true
  rules:
    - name: apply-restricted-pod-security
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  fleet.gitops/type: tenant
                  fleet.gitops/policy-pod-security: restricted
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              pod-security.kubernetes.io/enforce: restricted
              pod-security.kubernetes.io/audit: restricted
              pod-security.kubernetes.io/warn: restricted
    - name: apply-baseline-pod-security
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  fleet.gitops/type: tenant
                  fleet.gitops/policy-pod-security: baseline
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              pod-security.kubernetes.io/enforce: baseline
              pod-security.kubernetes.io/audit: baseline
              pod-security.kubernetes.io/warn: baseline