{{- if has .Values.cluster.environment .Values.namespace.env }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "namespace.name is required" .Values.namespace.name | quote }}
  labels:
    app.kubernetes.io/managed-by: argocd
    fleet.gitops/environment: {{ .Values.cluster.environment | quote }}
    fleet.gitops/owner: {{ .Values.namespace.owner | quote }}
    fleet.gitops/type: tenant
    {{ with .Values.namespace.policies }}
    {{ with .podSecurity }}
    fleet.gitops/policy-pod-security: {{ . | quote }}
    {{ end }}
    {{ end }}
    {{ range .Values.namespace.labels }}
    fleet.gitops/{{ . }}: "true"
    {{ end }}
  annotations:
    fleet.gitops/requested-by: {{ .Values.namespace.requestedBy | quote }}
    fleet.gitops/purpose: {{ .Values.namespace.purpose | quote }}
{{- end }}