apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-prod-limit-range
spec:
  background: true
  rules:
    - name: generate-prod-limit-range
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  fleet.gitops/type: tenant
                  fleet.gitops/environment: prod
      generate:
        synchronize: true
        apiVersion: v1
        kind: LimitRange
        name: tenant-defaults
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            limits:
              - type: Container
                defaultRequest:
                  cpu: 100m
                  memory: 128Mi
                default:
                  cpu: "1"
                  memory: 1Gi