apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: tenant-prod-resource-quota
spec:
  background: true
  rules:
    - name: generate-prod-resource-quota
      match:
        any:
          - resources:
              kinds:
                - Namespace
              selector:
                matchLabels:
                  fleet.gitops/type: tenant
                  fleet.gitops/environment: prod
      generate:
        synchronize: true
        apiVersion: v1
        kind: ResourceQuota
        name: tenant-resource-quota
        namespace: "{{request.object.metadata.name}}"
        data:
          spec:
            hard:
              requests.cpu: "2"
              requests.memory: 4Gi
              limits.cpu: "4"
              limits.memory: 8Gi
              pods: "20"
              services: "10"
              secrets: "20"
              configmaps: "20"