apiVersion: v1
kind: Namespace
metadata:
  name: platform-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability-agents
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
